#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
analyze_events.py
=================
This script analyses events in which participants reported 
perceived Problematic Algorithmic Behaviours (PBs)
during music-platform use.

Pipeline
--------
1.  Load raw EMA event data.
2.  Parse and map free-text PB selections to a structured taxonomy.
3.  Assess scale reliability (Cronbach α, item-total correlations).
4.  Revise the measurement model (SB4 → CI5).
5.  Descriptive summary table (events, PB prevalence, Likert means).
6.  Compute Spearman correlations between Likert outcome items.
7.  Co-occurrence analysis (Jaccard network + heatmap).
8.  Construct-level aggregation of conditional probabilities.
9.  Estimate conditional probabilities P(PB | context) with 95 % CIs.
10. Test differences across context levels via permutation tests
    (sign-flip Wilcoxon for 2-level; Friedman for ≥3-level).
11. Apply Benjamini–Hochberg FDR correction.
12. Effect size forest plot across contexts.
13. Visualise results as annotated heatmaps.
14. Export results to CSV.
15. Participant-level Likert × PB correlations.

Constructs
----------
SB  Societal Bias
CI  Commercial Interests
LD  Limited Discovery
O   Other / unclassified

Effect size conventions
-----------------------
INTENT   rank-biserial r  — positive = more frequent in ACTIVE than PASSIVE
TEMP     rank-biserial r  — positive = more frequent in PRE than POST
TRIGGERS Kendall's W      — always positive (0–1)

Input
-----
data/events_20260324.csv  (see config.RAW_EVENTS_PATH)

Output
------
outputs/figures/events/*.png   — all figures generated by this script
outputs/tables/events_enriched.csv
outputs/tables/construct_probs_{INTENT,TEMP,TRIGGERS}.csv
outputs/tables/conditional_probs_{INTENT,TEMP,TRIGGERS}.csv
outputs/tables/likert_pb_correlations.csv
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sns
from scipy.stats import friedmanchisquare, rankdata, spearmanr
from statsmodels.stats.multitest import multipletests
from statsmodels.stats.proportion import proportion_confint
from tqdm import tqdm

from config import (
    CONSTRUCT_COLORS,
    CONTEXT_LEVEL_ORDER,
    ENRICHED_EVENTS_PATH,
    EVENTS_FIGURES_DIR,
    PB_DICT,
    RAW_EVENTS_PATH,
    TABLES_DIR,
    ensure_output_dirs,
    setup_plot_style,
)
from plotting import save_and_show

setup_plot_style()


# ---------------------------------------------------------------------------
# Taxonomy helpers
# ---------------------------------------------------------------------------

def map_pb_list(statements: list[str]) -> list[tuple[str, int]]:
    """
    Map a list of Italian PB statements to (construct, item_id) tuples.

    Unrecognised statements fall back to ``("O", 2)``.

    Parameters
    ----------
    statements:
        Raw strings as selected by a participant.

    Returns
    -------
    list of (construct, item_id) tuples.
    """
    return [PB_DICT.get(s.strip(), ("O", 2)) for s in statements]


def remap_trigger(cat: str, num: int) -> str:
    """
    Apply the revised measurement model: SB4 is reassigned to CI5.

    Parameters
    ----------
    cat : construct label (e.g. ``"SB"``)
    num : item number

    Returns
    -------
    Column name string (e.g. ``"CI5"`` or ``"LD2"``).
    """
    if cat == "SB" and num == 4:
        return "CI5"
    return f"{cat}{num}"


def get_construct(trigger: str) -> str:
    """Return the construct prefix for a trigger column name."""
    for prefix in ("SB", "CI", "LD"):
        if trigger.startswith(prefix):
            return prefix
    return "O"


# ---------------------------------------------------------------------------
# Visualisation: stacked bar chart
# ---------------------------------------------------------------------------

def plot_trigger_temp_intent(df: pd.DataFrame) -> pd.DataFrame:
    """
    Horizontal stacked bar chart of TEMP x INTENT counts per platform TRIGGER,
    with a summary table appended below.
    Stacking order follows the canonical level ordering: PRE before POST,
    ACTIVE before PASSIVE within each temporal group.
    Parameters
    ----------
    df:
        Must contain columns ``TRIGGERS``, ``TEMP`` (PRE/POST),
        and ``INTENT`` (ACTIVE/PASSIVE).
    Returns
    -------
    Integer count table (DataFrame).
    """
    FONT_SIZE = 16
    TITLE_SIZE = 14

    counts = (
        df.groupby(["TRIGGERS", "TEMP", "INTENT"])
          .size()
          .reset_index(name="count")
    )
    triggers = counts["TRIGGERS"].unique()
    # Order: PRE ACTIVE, PRE PASSIVE, POST ACTIVE, POST PASSIVE
    color_map = {
        ("PRE",  "ACTIVE"):  "#87CEFA",
        ("PRE",  "PASSIVE"): "#1E90FF",
        ("POST", "ACTIVE"):  "#FFA07A",
        ("POST", "PASSIVE"): "#FF8C00",
    }
    table = (
        counts.pivot_table(
            index="TRIGGERS", columns=["TEMP", "INTENT"],
            values="count", fill_value=0,
        )
    )
    table.columns = [f"{t}_{i}" for t, i in table.columns]
    table = table.reset_index()
    table_int = table.copy()
    for col in table_int.columns[1:]:
        table_int[col] = table_int[col].astype(int)

    fig, ax = plt.subplots(figsize=(14, 6))
    bottom = np.zeros(len(triggers))
    for temp_intent, color in color_map.items():
        mask = (
            (counts["TEMP"]   == temp_intent[0]) &
            (counts["INTENT"] == temp_intent[1])
        )
        values = (
            counts[mask]
            .set_index("TRIGGERS")
            .reindex(triggers)["count"]
            .fillna(0)
        )
        ax.barh(triggers, values, left=bottom, color=color,
                label=f"{temp_intent[0]} {temp_intent[1]}")
        bottom += values

    # ax.set(xlabel="Count")

    ax.xaxis.label.set_size(FONT_SIZE)
    ax.tick_params(axis="both", labelsize=FONT_SIZE)
    ax.legend(title="TEMP x INTENT", loc="lower right",
              fontsize=FONT_SIZE, title_fontsize=TITLE_SIZE)
    ax.invert_yaxis()

    tbl = plt.table(
        cellText=table_int.values,
        colLabels=table_int.columns,
        loc="bottom", cellLoc="center",
        bbox=[0, -0.55, 1, 0.38],
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(FONT_SIZE)
    for (row, col), cell in tbl.get_celld().items():
        cell.set_height(0.07)

    plt.subplots_adjust(left=0.18, bottom=0.38)
    plt.tight_layout(rect=[0, 0.38, 1, 1])
    save_and_show(fig, EVENTS_FIGURES_DIR, "fig01_trigger_temp_intent.png")
    return table_int

# ---------------------------------------------------------------------------
# Descriptive summary table
# ---------------------------------------------------------------------------

def compute_descriptive_summary(
    df: pd.DataFrame,
    binary_mod_O_df: pd.DataFrame,
    pb_cols: list[str],
    likerts: list[str],
    pid_col: str = "PID",
) -> pd.DataFrame:
    """
    Produce a paper-ready descriptive summary table.

    Rows cover per-participant event counts, Likert means, and PB proportions,
    plus an OVERALL aggregate row.  Construct-level prevalence columns are
    appended as the mean of member item proportions.

    Parameters
    ----------
    df:
        Raw event-level DataFrame (must contain ``pid_col``, Likert columns,
        ``INTENT``, ``TEMP``, ``TRIGGERS``).
    binary_mod_O_df:
        Binary trigger matrix aligned with ``df`` index.
    pb_cols:
        Ordered list of PB trigger column names.
    likerts:
        Likert outcome column names.
    pid_col:
        Participant ID column.

    Returns
    -------
    summary_df:
        Wide-format summary DataFrame (also printed to stdout).
    """
    combined = pd.concat([df, binary_mod_O_df], axis=1)

    participant_rows = []
    for pid, grp in combined.groupby(pid_col):
        row: dict = {
            "ID":        pid,
            "N_events":  len(grp),
            "N_PRE":     int((grp["TEMP"]   == "PRE").sum()),
            "N_POST":    int((grp["TEMP"]   == "POST").sum()),
            "N_ACTIVE":  int((grp["INTENT"] == "ACTIVE").sum()),
            "N_PASSIVE": int((grp["INTENT"] == "PASSIVE").sum()),
        }
        for q in likerts:
            row[f"{q}_mean"] = round(grp[q].mean(), 2)
        for pb in pb_cols:
            row[f"{pb}_prop"] = round(grp[pb].mean(), 3)
        participant_rows.append(row)

    participant_df = pd.DataFrame(participant_rows).set_index("ID")

    overall: dict = {
        "ID":        "OVERALL",
        "N_events":  len(combined),
        "N_PRE":     int((combined["TEMP"]   == "PRE").sum()),
        "N_POST":    int((combined["TEMP"]   == "POST").sum()),
        "N_ACTIVE":  int((combined["INTENT"] == "ACTIVE").sum()),
        "N_PASSIVE": int((combined["INTENT"] == "PASSIVE").sum()),
    }
    for q in likerts:
        overall[f"{q}_mean"] = round(combined[q].mean(), 2)
    for pb in pb_cols:
        overall[f"{pb}_prop"] = round(combined[pb].mean(), 3)

    summary_df = pd.concat(
        [participant_df, pd.DataFrame([overall]).set_index("ID")]
    )

    for c in ("SB", "CI", "LD", "O"):
        cols = [p for p in pb_cols if get_construct(p) == c]
        if cols:
            summary_df[f"{c}_prevalence"] = (
                summary_df[[f"{p}_prop" for p in cols]].mean(axis=1).round(3)
            )

    print("\n=== Descriptive Summary Table ===")
    print(summary_df.to_string())
    return summary_df


# ---------------------------------------------------------------------------
# Reliability
# ---------------------------------------------------------------------------

def compute_reliability_wide_table(indf: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Compute Cronbach alpha, item-total correlations, and alpha-if-deleted for
    constructs SB, CI, and LD.

    Parameters
    ----------
    indf:
        Binary item matrix; columns named ``"SB1"``, ``"CI3"``, etc.

    Returns
    -------
    table_alpha:
        One row per construct with alpha and 95% confidence interval (2 d.p.).
        The interval column is labelled ``"Alpha_95CI"`` to avoid confusion
        with the CI (Commercial Interests) construct abbreviation.
    table_items:
        Two rows (item-total correlations / alpha-if-deleted) x all item
        columns (2 d.p.).
    """
    alpha_rows, itc_wide, aifd_wide = [], {}, {}

    for construct in ("SB", "CI", "LD"):
        items    = [c for c in indf.columns if c.startswith(construct)]
        df_items = indf[items]

        alpha_val, ci95 = pg.cronbach_alpha(df_items)
        alpha_rows.append({
            "Construct":  construct,
            "Alpha":      round(alpha_val, 2),
            "Alpha_95CI": f"[{round(ci95[0], 2)}, {round(ci95[1], 2)}]",
        })

        total = df_items.sum(axis=1)
        for col in items:
            itc_wide[col]  = round(df_items[col].corr(total - df_items[col]), 2)
            aifd_wide[col] = round(pg.cronbach_alpha(df_items.drop(columns=[col]))[0], 2)

    table_alpha = pd.DataFrame(alpha_rows)
    table_items = pd.DataFrame(
        [itc_wide, aifd_wide],
        index=["Item-total correlations", "Alpha if Deleted"],
    )
    return table_alpha, table_items


# ---------------------------------------------------------------------------
# Construct-level aggregation
# ---------------------------------------------------------------------------

def aggregate_to_construct_level(
    prob_df: pd.DataFrame,
    ci_df: pd.DataFrame,
    pb_cols: list[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Average item-level conditional probabilities and confidence interval bounds
    to construct level.

    Confidence interval bounds are averaged across items (conservative
    approximation).

    Parameters
    ----------
    prob_df:
        Item-level conditional probabilities
        (index = PB trigger, columns = context levels).
    ci_df:
        Item-level CI tuples, same shape as ``prob_df``.
    pb_cols:
        Ordered PB column list used to identify construct membership.

    Returns
    -------
    construct_prob_df:
        Construct-level probabilities (index = construct, columns = context).
    construct_ci_df:
        Construct-level CI tuples, same shape.
    """
    prob_rows: dict = {}
    ci_rows:   dict = {}

    for c in ("SB", "CI", "LD", "O"):
        items = [p for p in pb_cols if get_construct(p) == c]
        if not items or not all(i in prob_df.index for i in items):
            continue

        prob_rows[c] = prob_df.loc[items].mean()

        ci_lo = pd.DataFrame(
            {col: [ci_df.loc[i, col][0] for i in items] for col in ci_df.columns}
        ).mean()
        ci_hi = pd.DataFrame(
            {col: [ci_df.loc[i, col][1] for i in items] for col in ci_df.columns}
        ).mean()
        ci_rows[c] = {col: (float(ci_lo[col]), float(ci_hi[col]))
                      for col in ci_df.columns}

    construct_prob_df = pd.DataFrame(prob_rows).T
    construct_prob_df.index.name = "construct"

    construct_ci_df = pd.DataFrame(ci_rows).T
    construct_ci_df.index.name = "construct"

    return construct_prob_df, construct_ci_df


def plot_construct_level_probs(
    intent_c: pd.DataFrame,
    temp_c: pd.DataFrame,
    trigger_c: pd.DataFrame,
) -> None:
    """
    Grouped bar chart of construct-level P(PB | context) for all three
    context variables side by side.

    Column order within each panel follows the canonical level ordering:
    ACTIVE before PASSIVE (INTENT), PRE before POST (TEMP), TR1/TR2/TR3
    (TRIGGERS).  Each panel uses a distinct colour palette so the three
    context variables are visually separable at a glance.

    Parameters
    ----------
    intent_c:
        Construct-level probability DataFrame for listening intent
        (index = construct, columns = [ACTIVE, PASSIVE]).
    temp_c:
        Construct-level probability DataFrame for temporal context
        (index = construct, columns = [PRE, POST]).
    trigger_c:
        Construct-level probability DataFrame for perceptual trigger
        (index = construct, columns = [TR1, TR2, TR3]).
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)

    PANEL_PALETTES = [
        ["#4C72B0", "#87CEEB"],             # Blues for INTENT (ACTIVE, PASSIVE)
        ["#2CA02C", "#98DF8A"],             # Greens for TEMP (PRE, POST)
        ["#D62728", "#FF9896", "#FFCC99"],  # Reds/oranges for TRIGGERS (TR1, TR2, TR3)
    ]

    # Enforce canonical column ordering before plotting
    intent_c  = intent_c.reindex(columns=["ACTIVE", "PASSIVE"])
    temp_c    = temp_c.reindex(columns=["PRE", "POST"])

    panels = [
        (intent_c,  axes[0], "P(PB | INTENT)",   PANEL_PALETTES[0]),
        (temp_c,    axes[1], "P(PB | TEMP)",  PANEL_PALETTES[1]),
        (trigger_c, axes[2], "P(PB | TRIGGER)",   PANEL_PALETTES[2]),
    ]

    for cdf, ax, title, palette in panels:
        constructs = cdf.index.tolist()
        x      = np.arange(len(constructs))
        n_cols = len(cdf.columns)
        width  = 0.8 / n_cols

        for k, col in enumerate(cdf.columns):
            offset = (k - n_cols / 2 + 0.5) * width
            color  = palette[k] if k < len(palette) else plt.cm.tab10(k / n_cols)
            ax.bar(
                x + offset,
                cdf[col].astype(float),
                width=width,
                label=str(col),
                color=color,
                alpha=0.85,
            )

        ax.set_xticks(x)
        ax.set_xticklabels(constructs, fontsize=16)
        ax.set_title(title, fontsize=16)
        ax.set_ylabel("Mean P(PB)", fontsize=16)
        ax.set_ylim(0, 0.7)
        ax.legend(title="", fontsize=16)
        ax.axhline(0, color="black", linewidth=0.8)

    plt.tight_layout()
    save_and_show(fig, EVENTS_FIGURES_DIR, "fig02_construct_level_probs.png")


# ---------------------------------------------------------------------------
# Co-occurrence
# ---------------------------------------------------------------------------

def compute_coccurrence(indf: pd.DataFrame) -> None:
    """
    Compute pairwise Jaccard similarity between binary trigger columns and
    render a co-occurrence network (threshold >= 0.2) and a full heatmap.

    Parameters
    ----------
    indf:
        Binary trigger matrix (columns = trigger names).
    """
    cols    = indf.columns
    n       = len(cols)
    jaccard = np.zeros((n, n))

    for i, r in enumerate(cols):
        for j, c in enumerate(cols):
            inter = (indf[r] & indf[c]).sum()
            union = (indf[r] | indf[c]).sum()
            jaccard[i, j] = inter / union if union > 0 else 0

    jaccard_df = pd.DataFrame(jaccard, index=cols, columns=cols)
    print("Co-occurrence matrix (Jaccard):\n", jaccard_df)

    # Network
    G = nx.Graph()
    node_color_map = {"SB": "#4C72B0", "CI": "#DD8452", "LD": "#55A868"}
    for col in cols:
        G.add_node(col, color=node_color_map.get(col[:2], "#808080"))

    for i in cols:
        for j in cols:
            if i != j and jaccard_df.loc[i, j] >= 0.2:
                G.add_edge(i, j, weight=jaccard_df.loc[i, j])

    pos        = nx.circular_layout(G)
    colors     = [G.nodes[nd]["color"] for nd in G.nodes()]
    weights    = [G[u][v]["weight"] * 5 for u, v in G.edges()]
    edge_labels = {(u, v): f"{G[u][v]['weight']:.2f}" for u, v in G.edges()}

    fig_net = plt.figure(figsize=(10, 10))
    nx.draw_networkx_nodes(G, pos, node_color=colors, node_size=1200)
    nx.draw_networkx_labels(G, pos, font_size=10, font_color="white", font_weight="bold")
    nx.draw_networkx_edges(G, pos, width=weights, edge_color="#aaaaaa", alpha=0.7)
    nx.draw_networkx_edge_labels(
        G, pos,
        edge_labels=edge_labels,
        font_size=8,
        font_color="#333333",
        bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="none", alpha=0.7),
    )
    legend_handles = [
        mpatches.Patch(color="#4C72B0", label="SB - Societal Bias"),
        mpatches.Patch(color="#DD8452", label="CI - Commercial Imperatives"),
        mpatches.Patch(color="#55A868", label="LD - Limited Discovery"),
    ]
    plt.legend(handles=legend_handles, loc="upper left", bbox_to_anchor=(0.6, 1.1), borderaxespad=0, fontsize=16)
    plt.axis("off")
    save_and_show(fig_net, EVENTS_FIGURES_DIR, "fig03a_cooccurrence_network.png")

    # Heatmap
    fig_hm = plt.figure(figsize=(12, 10))
    sns.heatmap(jaccard_df, annot=True, fmt=".2f", cmap="Blues")
    save_and_show(fig_hm, EVENTS_FIGURES_DIR, "fig03b_cooccurrence_heatmap.png")


# ---------------------------------------------------------------------------
# Conditional probabilities
# ---------------------------------------------------------------------------

def conditional_prob_ci(
    df: pd.DataFrame,
    category_col: str,
    pb_cols: list[str],
    alpha: float = 0.05,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Compute P(PB | category) with binomial 95% confidence intervals
    (Clopper-Pearson beta method).

    Column order in the returned DataFrames follows ``CONTEXT_LEVEL_ORDER``
    for two-level context variables (INTENT: ACTIVE before PASSIVE; TEMP: PRE
    before POST).  For other variables (e.g. TRIGGERS) columns are sorted
    alphabetically, which yields TR1, TR2, TR3.

    Parameters
    ----------
    df:
        Event-level DataFrame containing ``category_col`` and all ``pb_cols``.
    category_col:
        Grouping variable (e.g. ``"INTENT"``).
    pb_cols:
        Binary PB trigger columns.
    alpha:
        Significance level for confidence intervals (default 0.05 -> 95%).

    Returns
    -------
    prob_df:
        Pivot table of probabilities (index = PB trigger, columns = categories).
    ci_tuples:
        Same shape as ``prob_df``; each cell holds ``(lower, upper)`` tuple.
    """
    records = []
    for cat, group in df.groupby(category_col):
        n = len(group)
        for pb in pb_cols:
            k = int(group[pb].sum())
            p_hat = k / n
            lo, hi = proportion_confint(count=k, nobs=n, alpha=alpha, method="beta")
            records.append({"category": cat, "PB_trigger": pb,
                             "probability": p_hat, "CI_lower": lo, "CI_upper": hi})

    result_df = pd.DataFrame(records)
    prob_df   = result_df.pivot(index="PB_trigger", columns="category", values="probability")
    ci_df     = result_df.pivot(index="PB_trigger", columns="category",
                                values=["CI_lower", "CI_upper"])

    # Enforce canonical column ordering
    if category_col in CONTEXT_LEVEL_ORDER:
        col_order = CONTEXT_LEVEL_ORDER[category_col]
        prob_df   = prob_df.reindex(columns=col_order)
        ci_df     = ci_df.reindex(columns=col_order, level=1)
    else:
        col_order = sorted(prob_df.columns)
        prob_df   = prob_df.reindex(columns=col_order)
        ci_df     = ci_df.reindex(columns=col_order, level=1)

    ci_tuples = pd.DataFrame(index=prob_df.index, columns=prob_df.columns)
    for r in prob_df.index:
        for c in prob_df.columns:
            ci_tuples.loc[r, c] = (ci_df["CI_lower"].loc[r, c],
                                   ci_df["CI_upper"].loc[r, c])
    return prob_df, ci_tuples


# ---------------------------------------------------------------------------
# Permutation tests
# ---------------------------------------------------------------------------

def permutation_test_conditional_prob(
    df_analysis: pd.DataFrame,
    pb_cols: list[str],
    context_col: str,
    n_permutations: int = 10000,
    apply_correction: bool = True,
    seed: int = 42,
) -> pd.DataFrame:
    """
    Permutation test for differences in P(PB | context) across context levels.

    Two-level contexts (INTENT, TEMP)
        Sign-flip permutation on participant-level differences.
        Effect size: rank-biserial r computed from the Wilcoxon W statistic
        (zero differences excluded per standard Wilcoxon treatment).
        Ranks are precomputed outside the loop for speed.
        Sign convention follows ``CONTEXT_LEVEL_ORDER``: positive r means
        higher endorsement in the first-listed level (ACTIVE for INTENT,
        PRE for TEMP).

    Multi-level contexts (TRIGGERS)
        Friedman test; effect size = Kendall's W = chi2_F / [n(k-1)].

    BH-FDR correction is applied across all PB triggers within each context
    variable; NaN p-values are excluded from correction.

    Parameters
    ----------
    df_analysis:
        Must contain ``"PID"``, ``context_col``, and all ``pb_cols``.
    pb_cols:
        Binary trigger columns to test.
    context_col:
        Categorical grouping variable.
    n_permutations:
        Number of permutation iterations.
    apply_correction:
        Whether to apply BH-FDR correction.
    seed:
        Random seed for reproducibility.

    Returns
    -------
    DataFrame with columns: ``PB``, ``observed_diff`` / ``observed_stat``,
    ``effect_size``, ``p_value``, ``p_value_corrected``, ``reject_null``.
    """
    rng = np.random.default_rng(seed)

    if context_col in CONTEXT_LEVEL_ORDER:
        context_levels = np.array(CONTEXT_LEVEL_ORDER[context_col])
        available = df_analysis[context_col].unique()
        missing   = [l for l in context_levels if l not in available]
        if missing:
            raise ValueError(
                f"Expected levels {context_levels} for '{context_col}', "
                f"missing: {missing}. Found: {available}"
            )
    else:
        context_levels = df_analysis[context_col].unique()

    results: list[dict] = []

    for pb in pb_cols:
        participant_probs = (
            df_analysis.groupby(["PID", context_col])[pb]
            .mean()
            .unstack()
            .reindex(columns=context_levels)
        )

        if len(context_levels) == 2:
            diffs = (
                participant_probs[context_levels[0]]
                - participant_probs[context_levels[1]]
            ).dropna()

            if len(diffs) < 3:
                results.append({"PB": pb, "observed_diff": np.nan,
                                 "effect_size": np.nan, "p_value": np.nan})
                continue

            diffs_nz = diffs[diffs != 0].values
            if len(diffs_nz) < 3:
                results.append({"PB": pb,
                                 "observed_diff": round(float(diffs.mean()), 4),
                                 "effect_size": 0.0, "p_value": 1.0})
                continue

            n_nz  = len(diffs_nz)
            max_w = n_nz * (n_nz + 1) / 2
            ranks = rankdata(np.abs(diffs_nz))
            w_obs = np.sum(ranks[diffs_nz < 0])
            r_obs = 1.0 - (2.0 * w_obs) / max_w

            # Vectorised sign-flip permutation: draws the exact same random
            # stream as the original `[rng.choice(...) for _ in range(n)]`
            # loop (numpy's Generator.choice consumes the bit stream
            # identically whether called once with `size=(n, k)` or n times
            # with `size=k`), so p-values are bit-for-bit unchanged while
            # avoiding a n_permutations-length Python loop per PB trigger.
            signs       = rng.choice([-1, 1], size=(n_permutations, n_nz))
            flipped     = diffs_nz[None, :] * signs
            w_null      = np.sum(ranks[None, :] * (flipped < 0), axis=1)
            null        = 1.0 - (2.0 * w_null) / max_w
            p_value = float(np.mean(np.abs(null) >= np.abs(r_obs)))

            results.append({
                "PB":            pb,
                "observed_diff": round(float(diffs.mean()), 4),
                "effect_size":   round(r_obs, 4),
                "p_value":       p_value,
            })

        else:
            participant_probs = participant_probs.dropna()

            if len(participant_probs) < 3:
                results.append({"PB": pb, "observed_stat": np.nan,
                                 "effect_size": np.nan, "p_value": np.nan})
                continue

            groups = [participant_probs[lvl].values for lvl in context_levels]

            if all(np.array_equal(groups[0], g) for g in groups[1:]):
                results.append({"PB": pb, "observed_stat": 0.0,
                                 "effect_size": 0.0, "p_value": 1.0})
                continue

            stat, p_value = friedmanchisquare(*groups)
            n, k          = len(participant_probs), len(context_levels)
            kendall_w     = stat / (n * (k - 1))

            results.append({
                "PB":            pb,
                "observed_stat": round(stat, 4),
                "effect_size":   round(kendall_w, 4),
                "p_value":       p_value,
            })

    results_df = pd.DataFrame(results)

    if apply_correction:
        valid = results_df["p_value"].notna()
        reject, p_corr, *_ = multipletests(results_df.loc[valid, "p_value"],
                                           method="fdr_bh")
        results_df["p_value_corrected"] = np.nan
        results_df["reject_null"]       = False
        results_df.loc[valid, "p_value_corrected"] = p_corr
        results_df.loc[valid, "reject_null"]        = reject

    return results_df


# ---------------------------------------------------------------------------
# Helper: build effect / p-value DataFrames for plotting
# ---------------------------------------------------------------------------

def build_effect_pval_dfs(
    perm_results: pd.DataFrame,
    pb_order: list[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Extract effect sizes and FDR-corrected p-values from permutation results,
    reindexed to ``pb_order``.

    Parameters
    ----------
    perm_results:
        Output of :func:`permutation_test_conditional_prob`.
    pb_order:
        Desired row order for the heatmap.

    Returns
    -------
    effect_df, pval_df: each a single-column DataFrame indexed by PB trigger.
    """
    indexed   = perm_results.set_index("PB")
    effect_df = indexed["effect_size"].reindex(pb_order).to_frame()
    pval_df   = indexed["p_value_corrected"].reindex(pb_order).to_frame()
    return effect_df, pval_df


# ---------------------------------------------------------------------------
# Significance helper
# ---------------------------------------------------------------------------

def _sig_stars(p: float) -> str:
    """Return APA-style significance stars for a p-value."""
    if p < 0.001: return "***"
    if p < 0.01:  return "**"
    if p < 0.05:  return "*"
    return ""


# ---------------------------------------------------------------------------
# Effect size forest plot
# ---------------------------------------------------------------------------

def plot_effect_size_forest(
    intent_results: pd.DataFrame,
    temp_results: pd.DataFrame,
    trigger_results: pd.DataFrame,
    pb_order: list[str],
) -> None:
    """
    Forest plot of effect sizes across all three context variables.

    INTENT and TEMP panels show rank-biserial r (range -1 to +1) with a
    dashed reference line at 0.  Positive r indicates higher endorsement in
    the first-listed condition (ACTIVE for INTENT, PRE for TEMP); negative r
    indicates higher endorsement in the second condition (PASSIVE and POST
    respectively).  TRIGGERS shows Kendall's W (range 0 to 1), which is
    always positive.

    Points are coloured by construct using ``CONSTRUCT_COLORS``.  Filled
    markers indicate FDR-corrected p < 0.05; open markers indicate
    non-significance.  Guide lines run from the reference line (0) to each
    point for readability.  Horizontal separator lines divide construct groups.

    Parameters
    ----------
    intent_results:
        Full permutation result DataFrame for INTENT context variable.
    temp_results:
        Full permutation result DataFrame for TEMP context variable.
    trigger_results:
        Full permutation result DataFrame for TRIGGERS context variable.
    pb_order:
        PB trigger names in display order (top to bottom).
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 10), sharey=True)

    panels = [
        (intent_results,  axes[0],
         "INTENT",  (-1, 1), 0),
        (temp_results,    axes[1],
         "TEMP",        (-1, 1), 0),
        (trigger_results, axes[2],
         "TRIGGERS",                                     (0,  1), None),
    ]

    y_pos = {pb: i for i, pb in enumerate(reversed(pb_order))}

    for results_df, ax, title, xlim, ref_line in panels:
        indexed = results_df.set_index("PB")

        for pb in pb_order:
            if pb not in indexed.index:
                continue

            y         = y_pos[pb]
            eff       = indexed.loc[pb, "effect_size"]
            p_corr    = indexed.loc[pb, "p_value_corrected"] \
                        if "p_value_corrected" in indexed.columns else np.nan
            construct = get_construct(pb)
            color     = CONSTRUCT_COLORS.get(construct, "#333333")

            if pd.isna(eff):
                ax.plot(0, y, marker="x", color="lightgray", markersize=8)
                continue

            significant = (not pd.isna(p_corr)) and (float(p_corr) < 0.05)
            face_color  = color if significant else "white"

            ax.plot(
                float(eff), y,
                marker="o", markersize=10,
                color=color,
                markerfacecolor=face_color,
                markeredgecolor=color,
                markeredgewidth=1.8,
                linestyle="None",
                zorder=3,
            )
            line_start = ref_line if ref_line is not None else xlim[0]
            ax.hlines(y, line_start, float(eff),
                      colors=color, linewidth=0.5, alpha=0.4, zorder=1)

        if ref_line is not None:
            ax.axvline(ref_line, color="black", linewidth=1.0,
                       linestyle="--", alpha=0.6)

        ax.set_xlim(xlim)
        ax.set_title(title, fontsize=16, pad=8)
        # ax.set_xlabel("Effect size", fontsize=10)
        ax.set_yticks(list(y_pos.values()))
        ax.set_yticklabels(list(reversed(pb_order)), fontsize=16)
        ax.grid(axis="x", alpha=0.3)

        sb_n    = sum(1 for p in pb_order if p.startswith("SB"))
        ci_n    = sum(1 for p in pb_order if p.startswith("CI"))
        ld_n    = sum(1 for p in pb_order if p.startswith("LD"))
        n_total = len(pb_order)
        for line_idx in (sb_n, sb_n + ci_n, sb_n + ci_n + ld_n):
            y_line = n_total - line_idx - 0.5
            if 0 <= y_line < n_total:
                ax.axhline(y_line, color="black", linewidth=1.5, zorder=2)

    legend_handles = [
        plt.Line2D([0], [0], marker="o", color="w",
                   markerfacecolor="white", markeredgecolor="gray",
                   markeredgewidth=1.8, markersize=9, label="p >= 0.05 (n.s.)"),
        plt.Line2D([0], [0], marker="o", color="w",
                   markerfacecolor="gray", markeredgecolor="gray",
                   markeredgewidth=1.8, markersize=9, label="p < 0.05 (FDR corrected)"),
    ]
    fig.legend(handles=legend_handles, loc="lower center", ncol=2,
               fontsize=9, bbox_to_anchor=(0.5, -0.04))
    plt.tight_layout()
    save_and_show(fig, EVENTS_FIGURES_DIR, "fig04_effect_size_forest.png")


# ---------------------------------------------------------------------------
# Visualisation: conditional probability heatmaps
# ---------------------------------------------------------------------------

def plot_conditional_distr_with_effects(
    intent_df: pd.DataFrame,
    temp_df: pd.DataFrame,
    trigger_df: pd.DataFrame,
    *,
    ci_intent_df:      pd.DataFrame | None = None,
    ci_temp_df:        pd.DataFrame | None = None,
    ci_trigger_df:     pd.DataFrame | None = None,
    effect_intent_df:  pd.DataFrame | None = None,
    effect_temp_df:    pd.DataFrame | None = None,
    effect_trigger_df: pd.DataFrame | None = None,
    pval_intent_df:    pd.DataFrame | None = None,
    pval_temp_df:      pd.DataFrame | None = None,
    pval_trigger_df:   pd.DataFrame | None = None,
    annotation: str = "effect",
    pb_order: list[str] | None = None,
) -> None:
    """
    Three-panel heatmap of P(PB | context) with 95% confidence interval
    annotations.

    Each cell displays ``prob / [lo, hi]``.  Effect size parameters are
    accepted for API compatibility but are not displayed in this plot; use
    :func:`plot_effect_size_forest` for effect size visualisation.

    Column order follows the canonical level ordering enforced by
    :func:`conditional_prob_ci`: ACTIVE before PASSIVE (INTENT), PRE before
    POST (TEMP), TR1/TR2/TR3 (TRIGGERS).  Black horizontal lines separate
    the SB / CI / LD / O construct groups.

    Parameters
    ----------
    intent_df:
        Conditional probability DataFrame for INTENT
        (index = PB trigger, columns = [ACTIVE, PASSIVE]).
    temp_df:
        Conditional probability DataFrame for TEMP
        (index = PB trigger, columns = [PRE, POST]).
    trigger_df:
        Conditional probability DataFrame for TRIGGERS
        (index = PB trigger, columns = [TR1, TR2, TR3]).
    ci_intent_df, ci_temp_df, ci_trigger_df:
        Matching DataFrames of ``(lower, upper)`` confidence interval tuples.
    effect_intent_df, effect_temp_df, effect_trigger_df:
        Accepted for API compatibility; not used in this plot.
    pval_intent_df, pval_temp_df, pval_trigger_df:
        Accepted for API compatibility; not used in this plot.
    annotation:
        Accepted for API compatibility; not used in this plot.
    pb_order:
        Accepted for API compatibility; row order is controlled by the
        index of the input DataFrames.
    """
    fig, axes = plt.subplots(1, 3, figsize=(24, 10))

    panels = [
        (intent_df,  ci_intent_df,  axes[0], "Blues",   "P(PB | INTENT)"),
        (temp_df,    ci_temp_df,    axes[1], "Greens",  "P(PB | TEMP)"),
        (trigger_df, ci_trigger_df, axes[2], "Oranges", "P(PB | TRIGGER)"),
    ]

    for prob_df, ci_df, ax, cmap, title in panels:
        annot = prob_df.copy().astype(str)

        for r in prob_df.index:
            for c in prob_df.columns:
                prob   = float(prob_df.loc[r, c])
                lo, hi = prob, prob
                if ci_df is not None:
                    cell = ci_df.loc[r, c]
                    if isinstance(cell, (tuple, list)) and len(cell) == 2:
                        lo, hi = float(cell[0]), float(cell[1])

                annot.loc[r, c] = f"{prob:.2f}\n[{lo:.2f},{hi:.2f}]"

        sns.heatmap(prob_df, cmap=cmap, annot=annot, fmt="", ax=ax, cbar=False)
        ax.set_title(title, fontsize=16, pad=10)
        ax.set_xlabel("", fontsize=16)
        ax.set_ylabel("", fontsize=16)

        sb_n = sum(1 for x in prob_df.index if str(x).startswith("SB"))
        ci_n = sum(1 for x in prob_df.index if str(x).startswith("CI"))
        ld_n = sum(1 for x in prob_df.index if str(x).startswith("LD"))
        for line in (sb_n, sb_n + ci_n, sb_n + ci_n + ld_n):
            if 0 < line < len(prob_df.index):
                ax.axhline(line, color="black", linewidth=2)

    plt.tight_layout()
    save_and_show(fig, EVENTS_FIGURES_DIR, "fig05_conditional_prob_heatmaps.png")


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

def export_conditional_results_csv(
    prob_df: pd.DataFrame,
    ci_df: pd.DataFrame,
    effect_df: pd.DataFrame,
    pval_df: pd.DataFrame,
    perm_results: pd.DataFrame,
    *,
    context_name: str,
    pb_order: list[str],
    output_path: str | Path,
) -> pd.DataFrame:
    """
    Write conditional probabilities, confidence intervals, effect sizes, and
    p-values to CSV.

    Columns per context level: ``{level}_prob``, ``{level}_ci_low``,
    ``{level}_ci_high``.  Final columns: ``effect_size``, ``p_value_raw``,
    ``p_value_corrected``, ``significance``.

    Parameters
    ----------
    prob_df:
        Conditional probabilities (index = PB, columns = context levels).
    ci_df:
        Confidence interval tuples, same shape as ``prob_df``.
    effect_df:
        Single-column effect sizes.
    pval_df:
        Single-column FDR-corrected p-values.
    perm_results:
        Full permutation results (provides raw p-values).
    context_name:
        Label used in print output only.
    pb_order:
        Row ordering for the output CSV.
    output_path:
        Destination file path.

    Returns
    -------
    The exported DataFrame (also written to ``output_path``).
    """
    perm_idx = perm_results.set_index("PB")
    rows: list[dict] = []

    for r in pb_order:
        row: dict = {
            "PB":        r,
            "construct": r[:2] if r != "O1" else "O",
        }

        for c in prob_df.columns:
            prob   = float(prob_df.loc[r, c])
            lo, hi = prob, prob
            if ci_df is not None:
                cell = ci_df.loc[r, c]
                if isinstance(cell, (tuple, list)) and len(cell) == 2:
                    lo, hi = float(cell[0]), float(cell[1])
            row[f"{c}_prob"]    = round(prob, 3)
            row[f"{c}_ci_low"]  = round(lo,   3)
            row[f"{c}_ci_high"] = round(hi,   3)

        if r in perm_idx.index:
            ev      = perm_idx.loc[r, "effect_size"] \
                      if "effect_size" in perm_idx.columns else np.nan
            pv_raw  = perm_idx.loc[r, "p_value"]
            pv_corr = perm_idx.loc[r, "p_value_corrected"] \
                      if "p_value_corrected" in perm_idx.columns else np.nan

            if pd.isna(ev) or pd.isna(pv_raw):
                row.update(effect_size=np.nan, p_value_raw=np.nan,
                            p_value_corrected=np.nan, significance="n/a")
            else:
                ev, pv_raw = float(ev), float(pv_raw)
                pv_corr    = float(pv_corr) if not pd.isna(pv_corr) else np.nan
                row.update(
                    effect_size       = round(ev, 3),
                    p_value_raw       = round(pv_raw, 3),
                    p_value_corrected = round(pv_corr, 3) if not pd.isna(pv_corr) else np.nan,
                    significance      = _sig_stars(pv_corr) if not pd.isna(pv_corr) else "",
                )
        else:
            row.update(effect_size=np.nan, p_value_raw=np.nan,
                        p_value_corrected=np.nan, significance="n/a")

        rows.append(row)

    out_df      = pd.DataFrame(rows).set_index("PB")
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_path)
    print(f"[export] {context_name} -> {output_path}")
    return out_df


# ---------------------------------------------------------------------------
# Likert x PB correlations
# ---------------------------------------------------------------------------

def compute_likert_pb_correlations(
    df: pd.DataFrame,
    likerts: list[str],
    pb_cols: list[str],
    pid_col: str = "PID",
    n_permutations: int = 10_000,
    seed: int = 42,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Participant-level Spearman correlations between Likert items and binary
    PB trigger proportions, with permutation-based p-values and BH-FDR
    correction applied within each Likert item separately.

    Each participant is reduced to one row by averaging Likert scores and PB
    proportions across all their events.  Ranks are precomputed outside the
    permutation loop (approx. 10x faster than calling ``spearmanr`` per
    iteration).

    BH-FDR is applied within each Likert item (13 tests per item) rather than
    across all 39 pairs, since each Likert item represents an independent
    research question.

    Parameters
    ----------
    df:
        Event-level DataFrame containing ``pid_col``, all ``likerts``,
        and all ``pb_cols``.
    likerts:
        Likert item column names.
    pb_cols:
        Binary PB trigger column names.
    pid_col:
        Participant ID column (default ``"PID"``).
    n_permutations:
        Number of permutation iterations (default 10 000).
    seed:
        Random seed for reproducibility.

    Returns
    -------
    corr_df:
        Observed Spearman rho (rows = Likert, columns = PB triggers), 3 d.p.
    pval_raw_df:
        Permutation p-values (not FDR corrected), same shape.
    pval_corr_df:
        BH-FDR corrected permutation p-values (within-Likert), same shape.
    """
    rng            = np.random.default_rng(seed)
    participant_df = df.groupby(pid_col)[likerts + pb_cols].mean()

    corr_df     = pd.DataFrame(index=likerts, columns=pb_cols, dtype=float)
    pval_raw_df = pd.DataFrame(index=likerts, columns=pb_cols, dtype=float)

    for q in likerts:
        likert_ranks = rankdata(participant_df[q].values)

        for pb in pb_cols:
            pb_ranks = rankdata(participant_df[pb].values)
            rho_obs  = float(np.corrcoef(likert_ranks, pb_ranks)[0, 1])

            # NOTE: this loop intentionally still calls np.corrcoef once per
            # permutation (rather than a manually-derived Pearson formula).
            # The two are mathematically equivalent but not bit-identical in
            # floating point; with 10,000 permutations, the tiny rounding
            # difference occasionally flips a null draw across the
            # significance threshold and shifts p-values in the fourth
            # decimal place. Verified against the original script on the
            # real dataset. Kept as-is to guarantee identical output.
            null_rhos = np.array([
                np.corrcoef(rng.permutation(likert_ranks), pb_ranks)[0, 1]
                for _ in tqdm(
                    range(n_permutations),
                    desc=f"Permuting {q} x {pb}",
                    leave=False,
                )
            ])

            corr_df.loc[q, pb]     = round(rho_obs, 3)
            pval_raw_df.loc[q, pb] = round(
                float(np.mean(np.abs(null_rhos) >= np.abs(rho_obs))), 4
            )

    pval_corr_df = pd.DataFrame(index=likerts, columns=pb_cols, dtype=float)
    for q in likerts:
        _, p_corr, *_ = multipletests(
            pval_raw_df.loc[q].astype(float).values,
            alpha=0.05, method="fdr_bh",
        )
        pval_corr_df.loc[q] = p_corr.round(4)

    return corr_df, pval_raw_df, pval_corr_df


def plot_likert_pb_heatmap(
    corr_df: pd.DataFrame,
    pval_corr_df: pd.DataFrame,
    pb_cols: list[str],
) -> None:
    """
    Heatmap of participant-level Spearman rho between Likert items and PB
    triggers, annotated with FDR-corrected significance stars.

    Vertical black lines separate SB / CI / LD construct groups.

    Parameters
    ----------
    corr_df:
        Spearman rho DataFrame (rows = Likert items, columns = PB triggers).
    pval_corr_df:
        BH-FDR corrected p-values (within-Likert), same shape as ``corr_df``.
    pb_cols:
        Ordered list of PB trigger names for separator line positions.
    """
    annot = corr_df.copy().astype(str)
    for q in corr_df.index:
        for pb in corr_df.columns:
            stars = _sig_stars(float(pval_corr_df.loc[q, pb]))
            annot.loc[q, pb] = f"{corr_df.loc[q, pb]:.2f}{stars}"

    fig, ax = plt.subplots(figsize=(14, 4))
    sns.heatmap(
        corr_df.astype(float),
        annot=annot, fmt="",
        cmap="coolwarm", center=0, vmin=-1, vmax=1,
        ax=ax, cbar_kws={"label": r"Spearman $\rho$"},
    )
    # ax.set_title(
    #     "* p < 0.05,  ** p < 0.01,  *** p < 0.001 -- FDR corrected per Likert item",
    #     fontsize=12,
    # )
    ax.set_xlabel("", fontsize=11)
    ax.set_ylabel("", fontsize=11)

    sb_n = sum(1 for c in pb_cols if c.startswith("SB"))
    ci_n = sum(1 for c in pb_cols if c.startswith("CI"))
    ld_n = sum(1 for c in pb_cols if c.startswith("LD"))
    for line in (sb_n, sb_n + ci_n, sb_n + ci_n + ld_n):
        if 0 < line < len(pb_cols):
            ax.axvline(line, color="black", linewidth=2)

    plt.tight_layout()
    save_and_show(fig, EVENTS_FIGURES_DIR, "fig06_likert_pb_heatmap.png")


def export_likert_pb_csv(
    corr_df: pd.DataFrame,
    pval_raw_df: pd.DataFrame,
    pval_corr_df: pd.DataFrame,
    output_path: str | Path,
) -> pd.DataFrame:
    """
    Export Spearman rho, raw and FDR-corrected permutation p-values, and
    significance stars to a long-format CSV.

    Parameters
    ----------
    corr_df:
        Spearman rho (rows = Likert items, columns = PB triggers).
    pval_raw_df:
        Raw permutation p-values, same shape.
    pval_corr_df:
        BH-FDR corrected p-values (within-Likert), same shape.
    output_path:
        Destination file path (parent directories created if needed).

    Returns
    -------
    Long-format DataFrame (also written to ``output_path``).
    """
    records = [
        {
            "likert":            q,
            "PB":                pb,
            "construct":         pb[:2] if pb != "O1" else "O",
            "spearman_rho":      float(corr_df.loc[q, pb]),
            "p_value_raw":       float(pval_raw_df.loc[q, pb]),
            "p_value_corrected": round(float(pval_corr_df.loc[q, pb]), 4),
            "significance":      _sig_stars(float(pval_corr_df.loc[q, pb])),
        }
        for q in corr_df.index
        for pb in corr_df.columns
    ]

    out_df      = pd.DataFrame(records)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_path, index=False)
    print(f"[export] Likert-PB correlations -> {output_path}")
    return out_df


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main(input_path: str | Path = RAW_EVENTS_PATH) -> None:
    """
    Run the full AA4MD analysis pipeline.

    Parameters
    ----------
    input_path:
        Path to the raw events CSV. Defaults to ``data/events_20260324.csv``
        (see ``config.RAW_EVENTS_PATH``).
    """
    ensure_output_dirs()

    # 1. Load data
    df = pd.read_csv(input_path)

    # 2. Visualise event distribution
    summary_table = plot_trigger_temp_intent(df)
    print(summary_table)

    # 3. Parse PB selections
    df["PB1_split"] = df["PB1"].str.split(",")
    df["PB2_split"] = df["PB2"].str.split(",")
    df["PB"] = df.apply(
        lambda row: (row["PB1_split"] if isinstance(row["PB1_split"], list) else [])
                  + (row["PB2_split"] if isinstance(row["PB2_split"], list) else []),
        axis=1,
    )
    df["PB_mapped"] = df["PB"].apply(map_pb_list)

    # 4. Original measurement model
    ORIG_COLS = ["SB1","SB2","SB3","SB4",
                 "CI1","CI2","CI3","CI4",
                 "LD1","LD2","LD3","LD4"]
    binary_df = pd.DataFrame(0, index=df.index, columns=ORIG_COLS)
    for i, row in df.iterrows():
        for cat, num in row["PB_mapped"]:
            col = f"{cat}{num}"
            if col in ORIG_COLS:
                binary_df.loc[i, col] = 1

    alpha_orig, items_orig = compute_reliability_wide_table(binary_df)
    print("=== Original model -- Cronbach alpha ===")
    print(alpha_orig)
    print("\n=== Original model -- Item statistics ===")
    print(items_orig)

    # 5. Revised model (SB4 -> CI5)
    REVISED_COLS = ["SB1","SB2","SB3",
                    "CI1","CI2","CI3","CI4","CI5",
                    "LD1","LD2","LD3","LD4"]
    binary_mod_df = pd.DataFrame(0, index=df.index, columns=REVISED_COLS)
    for i, row in df.iterrows():
        for col in (remap_trigger(cat, num) for cat, num in row["PB_mapped"]):
            if col in REVISED_COLS:
                binary_mod_df.loc[i, col] = 1

    alpha_mod, items_mod = compute_reliability_wide_table(binary_mod_df)
    print("\n=== Revised model -- Cronbach alpha ===")
    print(alpha_mod)
    print("\n=== Revised model -- Item statistics ===")
    print(items_mod)

    # 6. Likert inter-correlations + distributions
    df_analysis = pd.concat([df, binary_mod_df], axis=1)
    LIKERTS = ["ALGO_CAUSE", "FUTURE_USE", "ARTIST_HARM"]

    print("\nEvent-level Spearman correlations (Likert):")
    print(df_analysis[LIKERTS].corr(method="spearman"))

    df_melt = df_analysis[LIKERTS].melt(var_name="Likert", value_name="Score")
    fig_box = plt.figure(figsize=(8, 6))
    sns.boxplot(x="Likert", y="Score", data=df_melt, hue="Likert",
                dodge=False, palette="pastel", showfliers=True)
    sns.stripplot(x="Likert", y="Score", data=df_melt,
                  color="gray", size=4, jitter=True, alpha=0.6)
    plt.ylabel("Score")
    plt.xlabel("")
    plt.legend([], [], frameon=False)
    save_and_show(fig_box, EVENTS_FIGURES_DIR, "fig00_likert_distributions.png")

    summary = pd.DataFrame({
        "N":      df_analysis[LIKERTS].count(),
        "Mean":   df_analysis[LIKERTS].mean(),
        "SD":     df_analysis[LIKERTS].std(),
        "Median": df_analysis[LIKERTS].median(),
        "Q1":     df_analysis[LIKERTS].quantile(0.25),
        "Q3":     df_analysis[LIKERTS].quantile(0.75),
        "Min":    df_analysis[LIKERTS].min(),
        "Max":    df_analysis[LIKERTS].max(),
    }).round(2)

    print("\nDescriptive Statistics — Likert Items")
    print(summary.to_string())

    # 7. Build binary matrix including O category
    sb_cols = [c for c in binary_mod_df.columns if c.startswith("SB")]
    ci_cols = [c for c in binary_mod_df.columns if c.startswith("CI")]
    ld_cols = [c for c in binary_mod_df.columns if c.startswith("LD")]
    o_cols  = ["O1"]
    pb_cols = sb_cols + ci_cols + ld_cols + o_cols

    binary_mod_O_df = pd.DataFrame(0, index=df.index, columns=pb_cols)
    for i, row in df.iterrows():
        for col in (remap_trigger(cat, num) for cat, num in row["PB_mapped"]):
            if col in pb_cols:
                binary_mod_O_df.loc[i, col] = 1

    df_analysis_O = pd.concat([df, binary_mod_O_df], axis=1)

    # 7b. Export enriched event-level DataFrame
    event_enriched = df_analysis_O.drop(
        columns=["PB1_split", "PB2_split", "PB", "PB_mapped"],
        errors="ignore",
    )
    out_events = ENRICHED_EVENTS_PATH
    out_events.parent.mkdir(parents=True, exist_ok=True)
    event_enriched.to_csv(out_events, index=False)
    print(f"[export] Enriched events -> {out_events}")
    print(f"         Shape: {event_enriched.shape}")
    print(f"         Columns: {event_enriched.columns.tolist()}")

    # 8. Co-occurrence analysis
    print("\n=== Co-occurrence analysis (revised model) ===")
    compute_coccurrence(binary_mod_df)

    # 9. Conditional probabilities
    # Column order is enforced inside conditional_prob_ci via CONTEXT_LEVEL_ORDER:
    # INTENT -> [ACTIVE, PASSIVE]; TEMP -> [PRE, POST]; TRIGGERS -> [TR1, TR2, TR3]
    intent_probs,  intent_ci   = conditional_prob_ci(df_analysis_O, "INTENT",   pb_cols)
    temp_probs,    temp_ci     = conditional_prob_ci(df_analysis_O, "TEMP",     pb_cols)
    trigger_probs, trigger_ci  = conditional_prob_ci(df_analysis_O, "TRIGGERS", pb_cols)

    # 10. Construct-level aggregation + grouped bar chart
    intent_c,  intent_ci_c   = aggregate_to_construct_level(intent_probs,  intent_ci,  pb_cols)
    temp_c,    temp_ci_c     = aggregate_to_construct_level(temp_probs,    temp_ci,    pb_cols)
    trigger_c, trigger_ci_c  = aggregate_to_construct_level(trigger_probs, trigger_ci, pb_cols)

    print("\n=== Construct-level probabilities (INTENT) ===")
    print(intent_c.round(3))
    print("\n=== Construct-level probabilities (TEMP) ===")
    print(temp_c.round(3))
    print("\n=== Construct-level probabilities (TRIGGERS) ===")
    print(trigger_c.round(3))

    plot_construct_level_probs(intent_c, temp_c, trigger_c)

    for label, cdf in (("INTENT", intent_c), ("TEMP", temp_c), ("TRIGGERS", trigger_c)):
        p = TABLES_DIR / f"construct_probs_{label}.csv"
        cdf.round(3).to_csv(p)
        print(f"[export] Construct probs {label} -> {p}")

    # 11. Permutation tests
    intent_results  = permutation_test_conditional_prob(
        df_analysis_O, pb_cols, "INTENT",   n_permutations=10_000)
    temp_results    = permutation_test_conditional_prob(
        df_analysis_O, pb_cols, "TEMP",     n_permutations=10_000)
    trigger_results = permutation_test_conditional_prob(
        df_analysis_O, pb_cols, "TRIGGERS", n_permutations=10_000)

    # 12. Assemble plotting inputs
    pb_order = pb_cols

    intent_effect,  intent_pval  = build_effect_pval_dfs(intent_results,  pb_order)
    temp_effect,    temp_pval    = build_effect_pval_dfs(temp_results,    pb_order)
    trigger_effect, trigger_pval = build_effect_pval_dfs(trigger_results, pb_order)

    intent_probs  = intent_probs.reindex(pb_order)
    temp_probs    = temp_probs.reindex(pb_order)
    trigger_probs = trigger_probs.reindex(pb_order)
    intent_ci     = intent_ci.reindex(pb_order)
    temp_ci       = temp_ci.reindex(pb_order)
    trigger_ci    = trigger_ci.reindex(pb_order)

    # 13. Effect size forest plot
    plot_effect_size_forest(intent_results, temp_results, trigger_results, pb_order)

    # 14. Item-level conditional probability heatmaps
    plot_conditional_distr_with_effects(
        intent_probs, temp_probs, trigger_probs,
        ci_intent_df=intent_ci,           ci_temp_df=temp_ci,           ci_trigger_df=trigger_ci,
        effect_intent_df=intent_effect,   effect_temp_df=temp_effect,   effect_trigger_df=trigger_effect,
        pval_intent_df=intent_pval,       pval_temp_df=temp_pval,       pval_trigger_df=trigger_pval,
        pb_order=pb_order,
    )

    # 15. Export conditional probability CSVs
    for label, probs, ci, eff, pval, perm in (
        ("INTENT",   intent_probs,  intent_ci,  intent_effect,  intent_pval,  intent_results),
        ("TEMP",     temp_probs,    temp_ci,    temp_effect,    temp_pval,    temp_results),
        ("TRIGGERS", trigger_probs, trigger_ci, trigger_effect, trigger_pval, trigger_results),
    ):
        export_conditional_results_csv(
            probs, ci, eff, pval, perm,
            context_name=label,
            pb_order=pb_order,
            output_path=TABLES_DIR / f"conditional_probs_{label}.csv",
        )

    # 16. Participant-level Likert x PB correlations
    corr_df, pval_raw_df, pval_corr_df = compute_likert_pb_correlations(
        df_analysis_O, LIKERTS, pb_cols
    )

    print("\n=== Participant-level Spearman rho (Likert x PB) ===")
    print(corr_df)
    print("\n=== FDR-corrected p-values (within-Likert) ===")
    print(pval_corr_df)

    plot_likert_pb_heatmap(corr_df, pval_corr_df, pb_cols)

    export_likert_pb_csv(
        corr_df, pval_raw_df, pval_corr_df,
        output_path=TABLES_DIR / "likert_pb_correlations.csv",
    )


if __name__ == "__main__":
    main()